name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.12.0
          check-latest: true
      
      - name: Build VueJS Applicatoin
        run: npm run build
        
      - name: Simple FTP deploy
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ftp.xandervos.nl
          ftp_username: ${{ secrets.USERNAME }}
          ftp_password: ${{ secrets.PASSWORD }}
          local_source_dir: dist
          dist_target_dir: ${{ secrets.REMOTE_PATH }}
